### PR TITLE
Electron support

### PR DESCRIPTION
**Pull request by WilliamJenner**
Added electron support to the dashboard. Also updated webpack slightly

We can add this as a build step to the CI/CD server - [https://github.com/electron-userland/electron-builder
](https://github.com/electron-userland/electron-builder)

// TODO : Dev server, app settings / config

### CODE REVIEW

**Comment by harrygillingham99** [comment]
Looks awesome, do we still retain normal 'prod' web support two? Would be cool to output both from Jenkins

**Comment by WilliamJenner** [comment]
Electron loads it's window from a URL, so both web output and the desktop app is there

**Comment by harrygillingham99** [comment]
Thats even cooler! Does the dev server work now too, I saw some config stuff you did?

**Comment by WilliamJenner** [comment]
I've been upgrading webpack, turns out webpack-dev-server is outdated, and to use webpack serve.
Just been fixing the prod webpacking and appState config from appsettings.json, then i'm going to work on hot module replacement.

**Comment by WilliamJenner** [comment]
Dev server, app settings, and semi-HMR are now in!

**Pull request merged**
